logging.level.id.co.bca.intra: DEBUG

spring:
  application:
    name: serviceClientA

server:
  address: 127.0.0.1
  port: 8910

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8900/eureka}
  instance:
    preferIpAddress: true